project:
  type: website

website:
  title: "Data Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - cosmo
      - brand
    highlight-style: atom-one
    code-link: true
    css: styles.css

knitr:
  opts_chunk:
    collapse: true

