project:
  type: website

website:
  title: "Data Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    highlight-style: atom-one
    css: styles.css

knitr:
  opts_chunk:
    collapse: true

